#!/bin/bash

# AWS Production Deployment Script
# Task ID: 30ecd408b9cb4c38b98c4792c7283282

echo "=========================================="
echo "AWS PRODUCTION DEPLOYMENT STEPS"
echo "=========================================="
echo ""

TASK_ID="30ecd408b9cb4c38b98c4792c7283282"
CLUSTER="pythonide-cluster"
REGION="us-east-2"
CONTAINER="pythonide-backend"

echo "📋 STEP 1: Connect to AWS Container"
echo "Run this command to connect interactively:"
echo ""
echo "aws ecs execute-command \\"
echo "  --cluster $CLUSTER \\"
echo "  --task $TASK_ID \\"
echo "  --container $CONTAINER \\"
echo "  --command \"/bin/bash\" \\"
echo "  --interactive \\"
echo "  --region $REGION"
echo ""
echo "=========================================="
echo ""

echo "📋 STEP 2: Inside Container - Run Migration"
echo "Once connected, run these commands:"
echo ""
echo "cd /app/server"
echo "python3 migrations/create_full_class_with_consistent_passwords.py --environment production"
echo ""
echo "This will create all 42 users and show passwords in console"
echo ""
echo "=========================================="
echo ""

echo "📋 STEP 3: Expected Admin Passwords"
echo "These will be the production passwords:"
echo ""
echo "admin_editor: XuR0ibQqhw6#"
echo "sa9082: pXzwjLIYE20*"
echo "sl7927: 4qPg1cmJkUa!"
echo "et2434: evaTQRwfyhC*"
echo "test_admin: vheiJy81N8F#"
echo ""
echo "=========================================="
echo ""

echo "📋 STEP 4: Test Admin Interface"
echo "Navigate to:"
echo "https://pythonide-alb-456687384.us-east-2.elb.amazonaws.com/admin/users"
echo ""
echo "Login with: admin_editor / XuR0ibQqhw6#"
echo ""
echo "=========================================="
echo ""

echo "📋 STEP 5: Download Student Credentials"
echo "After running migration, get the CSV file:"
echo ""
echo "aws ecs execute-command \\"
echo "  --cluster $CLUSTER \\"
echo "  --task $TASK_ID \\"
echo "  --container $CONTAINER \\"
echo "  --command \"cat /app/adminData/consistent_class_credentials_production_*.csv\" \\"
echo "  --region $REGION > production_credentials.csv"
echo ""
echo "=========================================="
echo ""

echo "📋 ALTERNATIVE: Direct Container Commands"
echo "If interactive mode doesn't work, try:"
echo ""
echo "# Check if migration script exists:"
echo "aws ecs execute-command --cluster $CLUSTER --task $TASK_ID --container $CONTAINER --command \"ls -la /app/server/migrations/\" --region $REGION --interactive"
echo ""
echo "# Run migration directly:"
echo "aws ecs execute-command --cluster $CLUSTER --task $TASK_ID --container $CONTAINER --command \"cd /app/server && python3 migrations/create_full_class_with_consistent_passwords.py --environment production\" --region $REGION --interactive"
echo ""
echo "# Check users in database:"
echo "aws ecs execute-command --cluster $CLUSTER --task $TASK_ID --container $CONTAINER --command \"cd /app/server && python3 -c 'from common.database import db_manager; users = db_manager.execute_query(\\\"SELECT username, role FROM users ORDER BY role DESC, username\\\"); print(f\\\"Total users: {len(users)}\\\"); [print(f\\\"{u[\\\"role\\\"]}: {u[\\\"username\\\"]}\\\") for u in users[:5]]'\" --region $REGION --interactive"
echo ""
echo "=========================================="
echo ""

echo "📋 VERIFY: Check ECS Logs"
echo "aws logs tail /aws/ecs/pythonide --follow --region $REGION"
echo ""
echo "=========================================="