#!/bin/bash

echo "=========================================="
echo "AWS CONTAINER CONNECTION TROUBLESHOOTING"
echo "=========================================="
echo ""

TASK_ID="30ecd408b9cb4c38b98c4792c7283282"
CLUSTER="pythonide-cluster"
REGION="us-east-2"
CONTAINER="pythonide-backend"

echo "📋 STEP 1: Check Prerequisites"
echo "=========================================="
echo ""

echo "1. Install Session Manager Plugin (if not installed):"
echo "   https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html"
echo ""
echo "   For Mac:"
echo "   curl 'https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip' -o 'sessionmanager-bundle.zip'"
echo "   unzip sessionmanager-bundle.zip"
echo "   sudo ./sessionmanager-bundle/install -i /usr/local/sessionmanager -b /usr/local/bin/session-manager-plugin"
echo ""
echo "   For Linux:"
echo "   curl 'https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb' -o 'session-manager-plugin.deb'"
echo "   sudo dpkg -i session-manager-plugin.deb"
echo ""

echo "2. Check AWS CLI version (needs v1.16.12+ or v2):"
echo "   aws --version"
echo ""

echo "3. Verify AWS credentials are configured:"
echo "   aws sts get-caller-identity --region $REGION"
echo ""

echo "=========================================="
echo "📋 STEP 2: Debug ECS Execute Command"
echo "=========================================="
echo ""

echo "Check if execute command is enabled for the service:"
echo "aws ecs describe-services --cluster $CLUSTER --services pythonide-service --region $REGION --query 'services[0].enableExecuteCommand'"
echo ""

echo "Check task details:"
echo "aws ecs describe-tasks --cluster $CLUSTER --tasks $TASK_ID --region $REGION --query 'tasks[0].{EnableExecuteCommand:enableExecuteCommand,Status:lastStatus}'"
echo ""

echo "=========================================="
echo "📋 STEP 3: Alternative Connection Methods"
echo "=========================================="
echo ""

echo "METHOD A: Try with explicit ARN:"
echo "TASK_ARN=\$(aws ecs describe-tasks --cluster $CLUSTER --tasks $TASK_ID --region $REGION --query 'tasks[0].taskArn' --output text)"
echo "aws ecs execute-command --cluster $CLUSTER --task \$TASK_ARN --container $CONTAINER --command '/bin/bash' --interactive --region $REGION"
echo ""

echo "METHOD B: Force new deployment with execute enabled:"
echo "aws ecs update-service --cluster $CLUSTER --service pythonide-service --enable-execute-command --force-new-deployment --region $REGION"
echo "# Wait for new task to start, then get new task ID:"
echo "NEW_TASK_ID=\$(aws ecs list-tasks --cluster $CLUSTER --service-name pythonide-service --region $REGION --query 'taskArns[0]' --output text | rev | cut -d'/' -f1 | rev)"
echo "aws ecs execute-command --cluster $CLUSTER --task \$NEW_TASK_ID --container $CONTAINER --command '/bin/bash' --interactive --region $REGION"
echo ""

echo "=========================================="
echo "📋 STEP 4: ALTERNATIVE - Create API Endpoint"
echo "=========================================="
echo ""
echo "Since you can't connect directly, we can create a temporary API endpoint to run the migration:"
echo ""
echo "Option 1: Create a /api/admin/migrate endpoint"
echo "Option 2: Use the admin interface to trigger migration"
echo "Option 3: Add migration to startup script"
echo ""

echo "=========================================="
echo "📋 STEP 5: WORKAROUND - Use Admin Interface"
echo "=========================================="
echo ""
echo "The admin interface at /admin/users already has password management!"
echo ""
echo "1. Go to: https://pythonide-alb-456687384.us-east-2.elb.amazonaws.com/admin/users"
echo "2. Try logging in with one of these (they might already exist):"
echo "   - admin_editor / XuR0ibQqhw6#"
echo "   - sa9082 / pXzwjLIYE20*"
echo "   - sl7927 / 4qPg1cmJkUa!"
echo ""
echo "3. If login works, users might already be created!"
echo "4. If not, use 'Bulk Password Reset' to create all users"
echo ""

echo "=========================================="
echo "📋 STEP 6: Check if Users Already Exist"
echo "=========================================="
echo ""
echo "Try logging into the main app with these test accounts:"
echo "URL: https://pythonide-alb-456687384.us-east-2.elb.amazonaws.com"
echo ""
echo "Admin accounts to test:"
echo "  admin_editor / XuR0ibQqhw6#"
echo "  sa9082 / pXzwjLIYE20*"
echo ""
echo "If these work, the migration may have already run automatically!"
echo ""