# Local development with separate frontend/backend
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=pythonide
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pythonide-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pythonide
      - IDE_SECRET_KEY=local-dev-secret-key
      - IDE_DATA_PATH=/data/pythonide-data
      - PORT=8080
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/data:rw
    depends_on:
      - postgres
    networks:
      - pythonide-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8080
      - VUE_APP_WS_BASE_URL=ws://localhost:8080
    depends_on:
      - backend
    networks:
      - pythonide-network

volumes:
  postgres_data:

networks:
  pythonide-network:
    driver: bridge