#!/bin/bash

echo "PostgreSQL Setup Guide for PythonIDE"
echo "====================================="
echo ""
echo "Option 1: Using Docker (Recommended for development)"
echo "----------------------------------------------------"
echo "Run this command to start PostgreSQL in Docker:"
echo ""
echo "docker run -d \\"
echo "  --name pythonide-postgres \\"
echo "  -e POSTGRES_PASSWORD=postgres \\"
echo "  -e POSTGRES_DB=pythonide \\"
echo "  -p 5432:5432 \\"
echo "  postgres:15"
echo ""
echo "Option 2: Install PostgreSQL locally"
echo "------------------------------------"
echo "Ubuntu/Debian:"
echo "  sudo apt-get update"
echo "  sudo apt-get install postgresql postgresql-contrib"
echo ""
echo "macOS:"
echo "  brew install postgresql"
echo "  brew services start postgresql"
echo ""
echo "Then create the database:"
echo "  sudo -u postgres psql -c \"CREATE DATABASE pythonide;\""
echo "  sudo -u postgres psql -c \"ALTER USER postgres PASSWORD 'postgres';\""
echo ""
echo "Option 3: Use Railway PostgreSQL (Production)"
echo "---------------------------------------------"
echo "1. Deploy to Railway: railway up"
echo "2. Railway will automatically provision PostgreSQL"
echo "3. The DATABASE_URL will be set automatically"
echo ""
echo "After setting up PostgreSQL, run:"
echo "  cd server"
echo "  pip install -r requirements.txt"
echo "  python migrations/create_users.py"